# Generated by Django 2.2.12 on 2020-06-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newdatamodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newdatamodel',
            name='id3',
        ),
    ]
